services:
  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - "mongo-data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-password}"

  nextjs:
    build: .
    ports:
      - "${NEXT_PUBLIC_API_PORT:-3000}:3000"
    env_file:
      - .env.local
    environment:
      MONGODB_URI: "${MONGODB_URI:-mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-password}@${MONGO_SERVICE_NAME:-mongo}:27017/attorney_db?authSource=admin}"
      NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL:-http://localhost:${NEXT_PUBLIC_API_PORT:-3000}}"
    volumes:
      - .:/app
    depends_on:
      - "${MONGO_SERVICE_NAME:-mongo}"
    command: /bin/sh -c "if [ \"$SKIP_INIT_DB\" = \"true\" ]; then echo 'Skipping init-db'; else npm run init-db; fi && npm run dev"

volumes:
  mongo-data:
